### ISSUE TITLE
[FE] White Line between contact and footer section: Update the footer image

### ISSUE THREAD

**Issue by edichoska** [learnhubmk/app#258]
![Image](https://github.com/learnhubmkd/app/assets/105276163/46f4e637-8faa-4f17-9158-c53b11449d82)

UPDATE:
We will just update the image

**Comment by edichoska** [comment]
@kire21  There is an updated image in the Figma file, please check it and add it in the contact section.

**Comment by kire21** [comment]
@edichoska The image for mobile has not changed yet...

![Image](https://github.com/learnhubmk/app/assets/58231146/e3a51209-7a4d-4ce9-bfaf-cbb77a6945c1)

**Comment by edichoska** [comment]
@kire21 ahh :D Let me talk to the designers

**Comment by edichoska** [comment]
@kire21  Please check now. Just got the confirmation that they fixed it
