### ISSUE TITLE
[FE] Boarder on the Mission and Vision card - Dark mode web

### ISSUE THREAD

**Issue by sanjadivanisova** [learnhubmk/app#325]
Please remove the border from the Mission and Vision card in dark mode for web. There is currently a white border on the card. 

![Image](https://github.com/learnhubmk/app/assets/161955046/0553c26b-18a6-420b-82b7-96ffc565734e)

For reference, please look at Figma: 

https://www.figma.com/design/YLlXQlNrfYbBLOyOoIiEp3/learnhub?node-id=2496-3225&t=1cxD4Q8PJUVdjhej-0

**Comment by edichoska** [comment]
#326 @aleksandarmicev  you can do both of these on one PR
