### ISSUE TITLE
[FE] Add meta tag

### ISSUE THREAD

**Issue by edichoska** [learnhubmk/app#377]
this should be inside meta tag
name="google-site-verification" content="VGqmCtozF0vDHXcB3kwOVSGBOnbDFIOJq7Og2LgVe8E" 

![Image](https://github.com/learnhubmk/app/assets/105276163/7228f9b5-79d4-4000-8fec-749c0de7fe66)

**Comment by edichoska** [comment]
I am very confused about this. Is there a reason why a different value was added to the metatag? @Mikivitkovski @davorminchorov 
(I just changed it)


![Image](https://github.com/learnhubmk/app/assets/105276163/b94eda09-5935-4dea-addf-60069d76ba69)

**Comment by davorminchorov** [comment]
I generated a new key from the shared account so it was good.

**Comment by edichoska** [comment]
Ownership verification was failing with that key
